version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-user-manager
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: